spring.config.import=optional:file:.env[.properties]

spring.application.name=user-account-service
server.port=8081


#MYSQL DATABASE CONNECTION
#spring.datasource.url=${DB_URL_MYSQL}
#spring.datasource.username=${DB_USERNAME_MYSQL}
#spring.datasource.password=${DB_PASSWORD_MYSQL}

#JPA/Hibernate config
#spring.jpa.hibernate.ddl-auto=update


#POSTGRES DATABASE CONNECTION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update


#JWT CONFIG
jwt.secret=${JWT_SECRETE}
#I day expiration in millisec
jwt.expiration=${JWT_EXPIRATION}


# Actuator Config, Health Monitoring
management.endpoints.web.exposure.include=*


#Eureka Discovery Config
#eureka.client.server-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true


#kafka config
spring.kafka.bootstrap-servers=localhost:9092

#Kafka Config as a Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type=true


#KAFKA CONFIG AS CONSUMER
spring.kafka.consumer.group-id=account-group

#when the service is down and up again events that came in when it was down will be processed
spring.kafka.consumer.auto-offset-reset=earliest


spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=\
  com.example.transactionservice.kafka.dto.BalanceUpdateEvent:com.example.useraccountservice.kafka.dto.BalanceUpdateEvent






#EUREKA Discover
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/













